# -*- coding: utf-8 -*-
"""Copy of spacy_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7jvCCanEwExxGrZqw17ZtowZZN5Lux0
"""

!pip install spacy

import spacy

!python -m spacy download en_core_web_lg

nlp=spacy.load('en_core_web_lg')

text=nlp('spacy is a library')

"""1.Tokenization


"""

text

for token in text:
  print(token)

for token in text:
  print(type(token))

for token in text:
  print(type(token.text))

text=nlp("The cost of the Iphone in U.K is 627$")
text

for token in text:
  print(token)

## 2.POS- part of speech
for token in text:
  print(token.text, token.pos)

for token in text:
  print(token.text,token.pos_)

### 3. Sentence Tokenization
text=nlp('this is sentence one. this is sentence two. this is last now. lets study now')

for sent in text:
  print(sent)

import nltk

from nltk.tokenize import sent_tokenize
nltk.download('punkt')

import nltk
nltk.download('punkt_tab')

sent_tokenize('this is sentence one. this is sentence two. this is last now. lets study now')

from nltk.tokenize import word_tokenize
nltk.download('punkt')

word_tokenize('this is sentence one. this is sentence two. this is last now. lets study now')

'this is sentence one. this is sentence two. this is last now. lets study now'.split('.')